Repository gnoswap-labs/gnoswap, pull requests merged in 2024-10, with the labels that each got.

#354 fix-launchpad-deposit-reward
  __local/test/launchpad_test.mk
  launchpad/launchpad_deposit.gno
  launchpad/launchpad_reward.gno
  launchpad/tests/__TEST_launchpad_tier30_single_deposit_03_deposit_reward_by_deposit_test.gnoA
  launchpad/tests/__TEST_launchpad_tier30_single_deposit_04_deposit_reward_by_deposit_endheight_test.gnoA
  launchpad/type.gno
  launchpad/util.gno
Labels: bug

#356 GSW-1697 feat: distribute project pool reward if it has at least one deposit
  launchpad/launchpad_deposit.gno
  launchpad/launchpad_init.gno
  launchpad/launchpad_reward.gno
  launchpad/tests/__TEST_launchpad_create_project_test.gnoA
  launchpad/type.gno
Labels: enhancement

#361 GSW-1713-feat-transfer-left-amount-from-ended-project-by-admin
  launchpad/_RPC_api_deposit.gno
  launchpad/_RPC_api_project.gno
  launchpad/launchpad_init.gno
  launchpad/launchpad_reward.gno
  launchpad/tests/__TEST_RPC_api_test.gnoA
  launchpad/tests/__TEST_launchpad_create_project_test.gnoA
  launchpad/tests/__TEST_launchpad_deposit_project_single_recipient_test.gnoA
  launchpad/tests/__TEST_launchpad_deposit_project_two_recipient_test.gnoA
  launchpad/tests/__TEST_launchpad_refund_ended_proejct_no_deposit_test.gnoA
  launchpad/tests/__TEST_launchpad_refund_ended_proejct_with_tier30_test.gnoA
  launchpad/tests/__TEST_launchpad_tier180_single_deposit_reward_by_proejct_tier_test.gnoA
  launchpad/tests/__TEST_launchpad_tier30_single_deposit_01_deposit_collect_gns_test.gnoA
  launchpad/tests/__TEST_launchpad_tier30_single_deposit_02_deposit_reward_by_proejct_test.gnoA
  launchpad/tests/__TEST_launchpad_tier30_single_deposit_03_deposit_reward_by_deposit_test.gnoA
  launchpad/tests/__TEST_launchpad_tier30_single_deposit_04_deposit_reward_by_deposit_endheight_test.gnoA
  launchpad/tests/__TEST_launchpad_tier30_two_deposit_reward_by_project_test.gnoA
  launchpad/tests/__TEST_launchpad_tier90_single_deposit_reward_by_proejct_tier_test.gnoA
  launchpad/tests/__TEST_launchpad_two_project_two_tier_two_deposit_collect_gns_test.gnoA
  launchpad/type.gno
Labels: enhancement

#364 feat: Add `changelog.md` file
  .github/workflows/release.yml
  changelog.md
Labels: documentation
