Repository gnoswap-labs/gnoswap, pull requests merged in 2025-06, with the labels that each got.

#648 CI: Use gno before xform2 version
  .github/workflows/run_test.yml
Labels: ci

#647 fix: Apply interrealm to gov/governanace
  contract/r/gnoswap/emission/callback.gno
  contract/r/gnoswap/emission/distribution.gno
  contract/r/gnoswap/gov/governance/api_test.gno
  contract/r/gnoswap/gov/governance/config.gno
  contract/r/gnoswap/gov/governance/execute.gno
  contract/r/gnoswap/gov/governance/fn_registry.gno
  contract/r/gnoswap/gov/governance/fn_registry_test.gno
  contract/r/gnoswap/gov/governance/getter_vote.gno
  contract/r/gnoswap/gov/governance/proposal.gno
  contract/r/gnoswap/gov/governance/proposal_role.gno
  contract/r/gnoswap/gov/governance/proposal_state.gno
  contract/r/gnoswap/gov/governance/proposal_state_test.gno
  contract/r/gnoswap/gov/governance/proposal_test.gno
  contract/r/gnoswap/gov/governance/utils.gno
  contract/r/gnoswap/gov/governance/vote.gno
  contract/r/gnoswap/gov/governance/vote_test.gno
  contract/r/gnoswap/router/protocol_fee_swap.gno
  contract/r/gnoswap/staker/external_deposit_fee.gno
  contract/r/gnoswap/staker/manage_pool_tier_and_warmup.gno
  contract/r/gnoswap/staker/protocol_fee_unstaking.gno
Labels: governance

#664 ci: Fixed test execution
  .github/scripts/generate_matrix.rb
  .github/scripts/run_tests.rb
  .github/workflows/run_test.yml
  Gemfile
Labels: ci

#686 feat: add scenario tests and unit tests for GNS emission
  contract/r/gnoswap/gns/gns_test.gno
  contract/r/gnoswap/gns/halving.gno
  contract/r/gnoswap/gns/tests/gns_calculate_and_mint_test.gnoA
  contract/r/gnoswap/gns/tests/halving_year_mint_test.gnoA
  contract/r/gnoswap/gns/tests/z1_filetest.gnoA
  contract/r/gnoswap/gns/tests/z2_filetest.gnoA
  contract/r/gnoswap/gns/tests/z3_filetest.gnoA
  contract/r/gnoswap/gns/tests/z4_filetest.gnoA
  contract/r/gnoswap/gns/testutils.gno
  contract/r/gnoswap/gov/staker/staker.gno
  contract/r/gnoswap/staker/callback.gno
  contract/r/gnoswap/staker/staker.gno
  tests/scenario/gns/changed_halving_years_by_change_block_time_filetest.gno
  tests/scenario/gns/changed_halving_years_by_multiple_change_block_time_filetest.gno
  tests/scenario/gns/mint_gns_by_change_block_time_filetest.gno
  tests/scenario/gns/mint_gns_by_change_block_time_mid_year_rate25_filetest.gno
  tests/scenario/gns/mint_gns_by_change_block_time_mid_year_rate50_filetest.gno
  tests/scenario/gns/mint_gns_by_change_block_time_mid_year_rate75_filetest.gno
  tests/scenario/gns/mint_gns_by_copmlex_change_block_time_filetest.gno
  tests/scenario/gns/mint_gns_by_skipping_blocks_filetest.gno
  tests/scenario/gns/mint_gns_during_all_halving_years_filetest.gno
  tests/scenario/gns/verify_minted_gns_remaining_amount_filetest.gno
Labels: token
